CREATE TABLE BORROWER(ROLLIN INT,NAME VARCHAR(20),DATEOFISSUE DATE,NAMEOFBOOK VARCHAR(30),STATUS CHAR(1));

CREATE TABLE FINE(ROLL_NO INT,DATE DATE,AMT FLOAT);

INSERT INTO BORROWER VALUES(1,'Cameron','2017-07-19','DSA','I');
INSERT INTO BORROWER VALUES(2,'Kato','2017-07-01','COA','I');
INSERT INTO BORROWER VALUES(3,'Justine','2017-07-11','DBMS','I');
INSERT INTO BORROWER VALUES(4,'Yolanda','2017-08-22','TOC','I');
INSERT INTO BORROWER VALUES(5,'Brynne','2017-08-19','PPL','I');
INSERT INTO BORROWER VALUES(6,'Rigel','2017-08-04','CNE','I');

SELECT * FROM BORROWER;

DELIMITER //

CREATE PROCEDURE FINE_PROCEDURE(IN ROLL INT, IN B_NAME VARCHAR(20))
BEGIN
DECLARE DAYS,CNT,AMT INT;
SET AMT=0;
SET DAYS = DATEDIFF(CURRENT_DATE(),(SELECT DATEOFISSUE FROM BORROWER WHERE ROLLIN=ROLL AND NAMEOFBOOK=B_NAME));
IF DAYS>=15 THEN
SET CNT=15;
WHILE CNT<30 AND CNT<DAYS DO
SET AMT = AMT+5;
SET CNT = CNT+1;
END WHILE;
IF DAYS>30 THEN
SET CNT=30;
WHILE CNT<DAYS DO
SET AMT = AMT+50;
SET CNT=CNT+1;
END WHILE;
END IF;
INSERT INTO FINE VALUES(ROLL,CURRENT_DATE(),AMT);
END IF;
UPDATE BORROWER SET STATUS='R' WHERE ROLLIN=ROLL AND NAMEOFBOOK=B_NAME;
END//

DELIMITER ;

CALL FINE_PROCEDURE(1,'DSA');
CALL FINE_PROCEDURE(4,'TOC');
CALL FINE_PROCEDURE(46,'CNE');